# This workflow triggers auto-merge of any PR that dependabot creates so that
# PRs will be merged automatically without maintainer intervention if CI passes
name: Auto-merge dependabot PRs

on:
  # This is a risky trigger. Read the 4 posts that starts with
  # https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/.
  # Also read https://blog.yossarian.net/2024/12/06/zizmor-ultralytics-injection
  # for an real-world example.
  #
  # To mitigate risk we:
  # * Use a GitHub user without full crates.io ownership
  # * Avoid user-controlled inputs like github.head_ref. See TODO for full list.
  # * Avoid evaluating any dynamic input in shell context. Instead we do that in
  #   env context which is not prone to script injection TODO: source
  # * don't use the checkout action which by default includes a token TODO: ref
  pull_request_target:
    types: [opened]

jobs:
  auto-merge:
    # Warning! github.head_ref is user-controlled input. I don't think its
    # contents are evauluated in any way in the current context, however.
    if: github.repository == 'cargo-public-api/cargo-public-api' && github.event.pull_request.actor.login == 'app/dependabot'
    runs-on: ubuntu-latest
    environment:
      name: auto-merge
      url: https://github.com/cargo-public-api/cargo-public-api/blob/main/.github/workflows/Auto-merge-dependabot-PRs.yml
    env:
      GITHUB_TOKEN: ${{ secrets.AUTO_MERGE_GITHUB_TOKEN }}
    steps:
      - run: |
          gh pr review ${{ github.event.pull_request.number }} \
            --repo cargo-public-api/cargo-public-api \
            --comment \
            --body "If CI passes, this dependabot PR will be [auto-merged](https://github.com/cargo-public-api/cargo-public-api/blob/main/.github/workflows/Auto-merge-dependabot-PRs.yml) 🚀"
      - run: |
          gh pr merge \
            --repo cargo-public-api/cargo-public-api \
            --auto \
            --squash ${{ github.event.pull_request.number }}
